/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fushithemedicalaidapp;

import static fushithemedicalaidapp.AboutMnu.aboutTxtDisplay;
import static fushithemedicalaidapp.Controller.appMain;
import static fushithemedicalaidapp.Controller.extHelp;
import static fushithemedicalaidapp.Controller.intHelp;
import static fushithemedicalaidapp.InternalHelpMnu.intHelpTxtDisplay;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author gilli
 */
public class HelpMnu extends javax.swing.JFrame {
    FushiTheMedicalAidArray arr2 = new FushiTheMedicalAidArray();
    /**
     * Creates new form HelpMnu
     */
    public HelpMnu() {
        ///////////////////////////////////////////////////////////////////////
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\gilli\\OneDrive\\Documents\\NetBeansProjects\\FusiTHeMedicalAidApp\\HelpMnu.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(699, 515, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        setContentPane(new JLabel(imageIcon));
        ////////////////////////////////////////////////////////////////////////
        initComponents();
        ////////////////////////////////////////////////////////////////////////
        this.setLocationRelativeTo(null);
        ////////////////////////////////////////////////////////////////////////
        extBtn4.setContentAreaFilled(false);
        internalHelpMnuBtn.setContentAreaFilled(false);
        externalHelpMnuBtn.setContentAreaFilled(false);
        ////////////////////////////////////////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extBtn4 = new javax.swing.JButton();
        externalHelpMnuBtn = new javax.swing.JButton();
        internalHelpMnuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        extBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extBtn4ActionPerformed(evt);
            }
        });

        externalHelpMnuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalHelpMnuBtnActionPerformed(evt);
            }
        });

        internalHelpMnuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalHelpMnuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(internalHelpMnuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(externalHelpMnuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(extBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(internalHelpMnuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(externalHelpMnuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extBtn4ActionPerformed
        setVisible(false);// set HelpMnu invisible
        appMain.setLocationRelativeTo(null);
        appMain.setVisible(true);
    }//GEN-LAST:event_extBtn4ActionPerformed

    private void internalHelpMnuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalHelpMnuBtnActionPerformed
        setVisible(false);// set HelpMnu invisible
        intHelp.setLocationRelativeTo(null);
        intHelp.setVisible(true);
        arr2.FushiTheMedicalAidArray();
        intHelpTxtDisplay.setText(arr2.helpTxt());
    }//GEN-LAST:event_internalHelpMnuBtnActionPerformed

    private void externalHelpMnuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalHelpMnuBtnActionPerformed
        setVisible(false);// set HelpMnu invisible
        extHelp.setLocationRelativeTo(null);
        extHelp.setVisible(true);
    }//GEN-LAST:event_externalHelpMnuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpMnu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton extBtn4;
    private javax.swing.JButton externalHelpMnuBtn;
    private javax.swing.JButton internalHelpMnuBtn;
    // End of variables declaration//GEN-END:variables
}
