/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fushithemedicalaidapp;

import static fushithemedicalaidapp.Controller.appMain;
import static fushithemedicalaidapp.Controller.db;
import static fushithemedicalaidapp.Controller.lgn;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author gilli
 */
public class RegisterMnu extends javax.swing.JFrame {

    /**
     * Creates new form RegisterMnu
     */
    public RegisterMnu() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\gilli\\OneDrive\\Documents\\NetBeansProjects\\FusiTHeMedicalAidApp\\RegisterMnu.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(691, 517, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        setContentPane(new JLabel(imageIcon));
        initComponents();
        this.setLocationRelativeTo(null);
        //////////////////////////////////////////////////////////////////////
        backToLgnBtn.setContentAreaFilled(false);
        regBtn.setContentAreaFilled(false);
        //////////////////////////////////////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToLgnBtn = new javax.swing.JButton();
        regBtn = new javax.swing.JButton();
        userFieldN = new javax.swing.JTextField();
        userFieldSN = new javax.swing.JTextField();
        userFieldUN = new javax.swing.JTextField();
        userFieldIDN = new javax.swing.JTextField();
        userFieldMH = new javax.swing.JTextField();
        userFieldDOB = new javax.swing.JTextField();
        userFieldA = new javax.swing.JTextField();
        userFieldPW = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backToLgnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLgnBtnActionPerformed(evt);
            }
        });

        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        userFieldN.setBackground(new java.awt.Color(0, 162, 232));
        userFieldN.setBorder(null);
        userFieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldNActionPerformed(evt);
            }
        });

        userFieldSN.setBackground(new java.awt.Color(0, 162, 232));
        userFieldSN.setBorder(null);
        userFieldSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldSNActionPerformed(evt);
            }
        });

        userFieldUN.setBackground(new java.awt.Color(0, 162, 232));
        userFieldUN.setBorder(null);
        userFieldUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldUNActionPerformed(evt);
            }
        });

        userFieldIDN.setBackground(new java.awt.Color(0, 162, 232));
        userFieldIDN.setBorder(null);
        userFieldIDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldIDNActionPerformed(evt);
            }
        });

        userFieldMH.setBackground(new java.awt.Color(0, 162, 232));
        userFieldMH.setBorder(null);
        userFieldMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldMHActionPerformed(evt);
            }
        });

        userFieldDOB.setBackground(new java.awt.Color(0, 162, 232));
        userFieldDOB.setBorder(null);
        userFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldDOBActionPerformed(evt);
            }
        });

        userFieldA.setBackground(new java.awt.Color(0, 162, 232));
        userFieldA.setBorder(null);
        userFieldA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldAActionPerformed(evt);
            }
        });

        userFieldPW.setBackground(new java.awt.Color(0, 162, 232));
        userFieldPW.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backToLgnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 466, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userFieldA)
                    .addComponent(userFieldDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userFieldIDN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userFieldUN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userFieldSN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userFieldN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userFieldMH, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(userFieldPW))
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToLgnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(userFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(userFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userFieldUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(userFieldPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userFieldIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(userFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(userFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(userFieldMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToLgnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLgnBtnActionPerformed
        setVisible(false);// set LoginMnu invisible
        lgn.setLocationRelativeTo(null);
        lgn.setVisible(true);
    }//GEN-LAST:event_backToLgnBtnActionPerformed

    private void userFieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldNActionPerformed

    private void userFieldSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldSNActionPerformed

    private void userFieldUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldUNActionPerformed

    private void userFieldIDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldIDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldIDNActionPerformed

    private void userFieldMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldMHActionPerformed

    private void userFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldDOBActionPerformed

    private void userFieldAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldAActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        db.register(userFieldN.getText(), userFieldSN.getText(), userFieldUN.getText(), userFieldPW.getText(), userFieldIDN.getText(), userFieldDOB.getText(), userFieldA.getText(), userFieldMH.getText());
        userFieldN.setText("");
        userFieldSN.setText("");
        userFieldUN.setText("");
        userFieldPW.setText("");
        userFieldIDN.setText("");
        userFieldDOB.setText("");
        userFieldA.setText("");
        userFieldMH.setText("");
        setVisible(false);// set LoginMnu invisible
        appMain.setLocationRelativeTo(null);
        appMain.setVisible(true);// set AppMnu visible
    }//GEN-LAST:event_regBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterMnu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterMnu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToLgnBtn;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField userFieldA;
    private javax.swing.JTextField userFieldDOB;
    private javax.swing.JTextField userFieldIDN;
    private javax.swing.JTextField userFieldMH;
    private javax.swing.JTextField userFieldN;
    private javax.swing.JTextField userFieldPW;
    private javax.swing.JTextField userFieldSN;
    private javax.swing.JTextField userFieldUN;
    // End of variables declaration//GEN-END:variables
}
